### ISSUE TITLE
SCMIR doesn't seem to be in the sc3 plugs folder

### ISSUE THREAD

**Issue by unculcated** [allenloves/SuperSampler#13]
Only SCMIRUGens

so I get ;

Execution warning: Class 'SCMIR' not found
ERROR: Message 'framehop' not understood.

**Comment by allenloves** [comment]
SCMIR is not included in SuperSampler and it is not registered as a Quark by the author.  Therefore you have to go to his website and download/install it manually.

http://composerprogrammer.com/code.html

**Comment by allenloves** [comment]
I have solved the SCMIR issue.  Right now the necessary functions in SCMIR is included in SuperSampler.  Downloading the Quark should work.
