### ISSUE TITLE
Server 'localhost' exited with exit code 0. [Bug]

### ISSUE THREAD

**Issue by buscon** [allenloves/SuperSampler#15]
hi,

first thanks for the great work, I'm looking forward to use your library!

I am trying to use  the example in the help file. I can load the file successfully, but when I try to play it with:
Sampler(\rain).key;  //play a random keynote
I get:
 -> a SamplerArguments
Server 'localhost' exited with exit code 0.
server 'localhost' disconnected shared memory interface

So the server crashes. I reboot the server, when I load it again it says:
-> localhost
WARNING: This file is already loaded
and when I try to play it:
-> a SamplerArguments
Buffer UGen: no buffer data
Buffer UGen: no buffer data

I am using Supercollider 3.10.3 on Linux Mint.

Any ideas what the problem can be?

**Comment by allenloves** [comment]
I just solved the reloading problem.  Please update the Quark.

On the other hand I still don't know what causes the server to crash.   I never tested the sampler with a big sound file.  Is your sound file big?

Please try the example again and let me know if it still crashes the server.  In the mean time let me do some more research...

Best,
Allen

**Comment by allenloves** [comment]
Found the issue.
The SCMIR pitch detection functions differently in linux that causes this error. 
It has been fixed.  Please update your SuperSampler

Thank you very much.

Best,
Allen

**Comment by buscon** [comment]
Thank you Allen for fixing the problem, now it works perfectly.
