### ISSUE TITLE
Sampler class

### ISSUE THREAD

**Issue by dyfer** [allenloves/SuperSampler#16]
Hello,
I have encountered two quarks that both use a class called `Sampler`. TL;DR installing both quarks results in a duplicate class and prevents SC class library from compiling.

While there's no policy about naming classes in Quarks and duplicates are possible/unavoidable, I'd like to submit this information to possibly encourage the use of more specific class names in each respective quark.
I'm submitting this information for both quarks. I understand that solving this might not be possible, but I thought I'd raise awareness about this. The two quarks are:
- [Scintillator](https://github.com/ScintillatorSynth/Scintillator)
- [SuperSampler](https://github.com/allenloves/SuperSampler)

**Comment by allenloves** [comment]
Hi Marcin,

Thank you for reporting this.  I guess eventually this is going to happen.
I will see what I can do.  It might take some time to change and test my
code.

Best,
Allen
