### ISSUE TITLE
duplicate class causes compilation failure

### ISSUE THREAD

**Issue by danielfennelly** [allenloves/SuperSampler#18]
It looks like the move from `Sampler.sc` over to `SSampler.sc` was incomplete, leading to a Quark which can't be compiled. This also then prevents the opening of the Quarks dialog until the error is manually fixed.

```
ERROR: duplicate Class found: 'SSampler' 
/Users/danielfennelly/Library/Application Support/SuperCollider/downloaded-quarks/SuperSampler/SSampler.sc
/Users/danielfennelly/Library/Application Support/SuperCollider/downloaded-quarks/SuperSampler/Sampler.sc
```

I believe this will be resolved by simply deleting `Sampler.sc`

**Comment by allenloves** [comment]
Thank you so much.  I will fix it asap.

Best,
Allen
