### ISSUE TITLE
How to Get Started with SuperSampler?

### ISSUE THREAD

**Issue by spellfish** [allenloves/SuperSampler#9]
Hello Allen!

It's been a while. We were in the SuperCollider CCRMA class together. I'm wondering how I can get started with running SuperSampler locally. Do you have a decent help file I can reference?

**Comment by allenloves** [comment]
Do you know how to install extensions in SuperCollider?

**Comment by allenloves** [comment]
Do you know how to install extensions in SuperCollider?

I wrote a new instruction about installing SuperSampler on readme.md.   Please let me know if you have further questions.
